# Generated by Django 4.1 on 2022-08-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Adı')),
                ('last_name', models.CharField(max_length=50, verbose_name='Soyadı')),
                ('age', models.IntegerField(verbose_name='Yas')),
                ('number', models.IntegerField(verbose_name='Numara')),
                ('section', models.CharField(max_length=10, verbose_name='Sınıfı')),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Öğrenciler',
                'ordering': ['number'],
            },
        ),
    ]
