# Generated by Django 4.1 on 2022-08-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('august', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Adı')),
                ('last_name', models.CharField(max_length=50, verbose_name='Soyadı')),
                ('age', models.IntegerField(verbose_name='Yas')),
                ('sicili', models.IntegerField(verbose_name='Sicili')),
                ('field', models.CharField(max_length=10, verbose_name='Uzmanlık Alanı')),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Öğretmenler',
                'ordering': ['sicili'],
            },
        ),
    ]
